version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code

    ports:
      - 80:8000

    links:
      - redis:redis

    expose:
      - 8000

    user: 1001:1002 ## needed for linux

    #command: python /code/realTimeChatCrypto/manage.py runserver 0.0.0.0:8000
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application


  redis:
    image: redis:latest
    expose:
      - 6379
