version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
       - .:/code

    #ports:
      #- 80:8000

    links:
      - redis:redis

    expose:
      - 8000

    user: 1001:1002 ## needed for linux

    #working_dir: /code/realTimeChatCrypto
    command: python /code/realTimeChatCrypto/manage.py runserver 0.0.0.0:8000
    #command: daphne -b 0.0.0.0 -p 8000 realTimeChatCrypto.asgi:application


  redis:
    image: redis:latest
    expose:
      - 6379

  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./realTimeChatCrypto/static/:/static
    depends_on:
      - web
    ports:
      - 80:80
      #- 443:443
    links:
      - web:web
