version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code

    links:
      - redis:redis

    expose:
      - 8000

    #command: python /code/realTimeChatCrypto/manage.py runserver 0.0.0.0:8000
    command: daphne -b 0.0.0.0 -p 8000 realTimeChatCrypto.asgi:application

  redis:
    image: redis:latest
    expose:
      - 6379
