# Generated by Django 4.0 on 2021-12-10 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestionText', models.CharField(max_length=400)),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(max_length=200, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('imageDescription', models.CharField(max_length=240, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=400)),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.suggestionmodel')),
            ],
        ),
    ]
